services:

  improvement:
    build:
      dockerfile: DockerfileIMP
    env_file:
      - .env
    command:
      - "python"
      - "-m"
      - "improvement.listener"

  recognition:
    build:
      dockerfile: DockerfileREC
    env_file:
      - .env
    command:
      - "python"
      - "-m"
      - "recognition.listener"

  restapi:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      - "python"
      - "-m"
      - "api.main"